apiVersion: v1
kind: Service
metadata:
  name: moniflux-service
spec:
  selector:
    app: moniflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: api
    - protocol: TCP
      port: 9098
      targetPort: 9098
      name: loadgen
  type: LoadBalancer
