# backend/Dockerfile.loadgen

# Stage 1: Build the Go application
FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/loadgen cmd/loadgen/main.go

# Stage 2: Create the final image
FROM alpine:latest
WORKDIR /app

RUN mkdir -p /app/configs
COPY --from=builder /app/bin/loadgen .
EXPOSE 9080

CMD ["./loadgen"]
